bot:
  id: ""
  appId: ""
  token: ""
  secret: ""
  public: false
  debug: false
adminToken: ""
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
mongodb:
  host: ""
  port: 27017
  user: ""
  password: ""
  db: ""
debug: false
